### ISSUE TITLE
분리배출 데이터 동기화

### ISSUE THREAD

**Issue by GomDue** [BUNRI-WIKI/project-workflow#1]
---
name: Issue Template
about: Issue template for MIDAS projects
title: 분리배출 데이터 동기화
labels: Feat 1
assignees: GomDue
---

## Description
> 매일 자정마다 구글 드라이브 내 공유 파일을 데이터베이스로 전송
## To-Do
- [x] Airflow DAG 설정 변경
- [x] GCP 와 Airflow 연결
- [x] AWS RDS 와 Airflow 연결
- [x] Apache Spark와 Airflow 연결
- [x] 데이터베이스에 데이터 삽입 쿼리 작성

## Reference
