### ISSUE TITLE
 ML 모델 학습 워크플로 개발

### ISSUE THREAD

**Issue by GomDue** [BUNRI-WIKI/project-workflow#5]
---
name: Issue Template
about: Issue template for MIDAS projects
title: ML 모델 학습 워크플로 개발
labels: Feat 3
assignees: GomDue
---

## Description
> ML 모델 학습을 위한 워크플로 개발 및 관련 패키지 구현
## To-Do
- [x] YOLO 및 Transformer 모델 load 
- [x] XCom을 통한 정상적인 모델 load 확인 및 처리
- [x] 모델 초기화 및 설정
- [x] 모델 훈련 코드 최적화
- [x] 모델의 하이퍼파라미터 및 loss, accuracy 등 평가지표 추적을 위한 TensorBoard log 생성
- [x] TensorBoard에 기록할 평가지표 선정
- [x] KcBert 모델 학습 결과 및 저장소 구축
- [x] YOLO 모델의 학습 결과 및 데이터셋을 TensorBoard에 기록

## Reference
